### ISSUE TITLE
Matcher.Matches() fails with a basedir of "."

### ISSUE THREAD

**Issue by hairyhenderson** [zealic/xignore#3]
The [`Matcher.Matches`](https://pkg.go.dev/github.com/zealic/xignore#Matcher.Matches) method errors when given `.` as the basedir. This may be expected behaviour (and may well be desirable so that `xignore` doesn't need to call `os.Getwd`), but it's undocumented.

See https://github.com/hairyhenderson/gomplate/pull/1082 for a bit of background on how I found it (and worked around it).

I'm not sure if this is something that `xignore` should handle, but it should at least be documented 😉

**Comment by zealic** [comment]
I see you was processed this issue in https://github.com/hairyhenderson/gomplate/pull/1082 .

I think this issue should really be handled by the caller, because the library does not know the context of the calling scene and cannot control it.
I'm glad you already dealt with this issue.

I will add document for this api context.
